server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    perferIpAddress:  true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
