server:
  port: 8081
spring:
  application:
    name: zuul-Service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #  隐藏所有微服务名称(即使用微服务名称无法访问到服务)
  ignored-services: "*"
  #  服务前缀名，想要访问项目之前要加上此路径
  prefix: /hykd
  routes:
#   想要被替换的服务名称(con. 自己取得名字)
    my.serviceId: user-Service
#    替换后访问的名称
    my.path: /user/**
    my1.serviceId: data-Service
    my1.path: /data/**





